### PR TITLE
Update depends.txt

### PR DESCRIPTION
**Pull request by MidnightPhantom**
nothing just removed mcl_core

### CODE REVIEW

**Comment by MidnightPhantom** [comment]
Hey man could you give the list of items that in someway or the other depend on mcl_core

**Comment by TechNolaByte** [comment]
absolutely no idea what mcl_core is doing in the dependency list

**Comment by TechNolaByte** [comment]
ok so seems like mcl_core is used for support with mcl wood types in the storage drawers something something

**Comment by TechNolaByte** [comment]
which i got by reading the changelog

**Comment by MidnightPhantom** [comment]
So I think I will remove those someday or maybe you could

**Comment by MidnightPhantom** [comment]
Well if you change the lines this mod is reasonable

**Comment by TechNolaByte** [comment]
haha not really, this mod is an absurd abomination never really intended for anyone else's use. An unholy amalgamation of random code I copied, modified, and wrote myself back when I was still learning and when I thought it would be fun to add feature xyz to my skyblock world.

**Pull request merged**
